login/basic/urls.py
from django.urls import path
from . import views

app_name = 'basic'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('login/', views.login_page, name='login'),
    path('registration/', views.register, name='register'),
    path('logout/', views.logout_page, name='logout')
]

login/login/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic/', include('basic.urls')),

]

login/basic/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthdate = models.DateField(blank=True)

login/basic/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','password')


class UserProfileForm(forms.ModelForm):

    class Meta():
        model = UserProfile
        fields = ('birthdate',)

login/basic/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def homepage(request):
    cont = {}
    return render(request, 'basic/homepage.html', cont)


def login_page(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                print('Logged in')
                return HttpResponseRedirect(reverse('basic:home'))
            else:
                return HttpResponse("Your account is not active")

        else:
            return HttpResponse('Login Failed')

    else:
        return render(request, 'basic/login.html',{})


def register(request):

    registered = False

    if request.method == "POST":

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            if 'birthdate' in request.POST:
                profile = profile_form
                profile.save(commit=False)
                profile.user = user
                profile.save()

            registered = True
            print('it is OK!')
        else:
            print(user_form.errors, profile_form.errors)
            return HttpResponse('something is wrong')
    else:
        user = UserForm()
        profile = UserProfileForm()

    return render(request, 'basic/register.html', {'user': user, 'profile': profile, 'registered': registered})


@login_required
def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic:home'))

login/templates/basic/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to login/logout exercise!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic:home' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basic:register' %}">Register</a>

          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'basic:logout' %}">Logout</a>
          {% else %}
            <a class="nav-link" href="{% url 'basic:login' %}">Login</a>
          {% endif %}
      </div>
    </nav>
<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

login/templates/basic/login.html
{% extends 'basic/homepage.html' %}
{% block body %}
    <div class="jumbotron">
        <h1>Please, log in!</h1>

        <form method="post" action="{% url 'basic:login' %}">
            {% csrf_token %}

            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Your Username">

            <label for="password">Password</label>
            <input type="text" name="password" placeholder="Enter Your Password">

            <input type="submit" value="Login">
        </form>
    </div>
{% endblock %}

login/templates/basic/register.html
{% extends "basic/homepage.html" %}

{% block body %}
<form method="POST" action="{% url 'basic:register' %}" enctype="multipart/form-data">
    {% csrf_token %}

    {% if registered %}
    <h1>Thanks for registration!</h1>

    {% else %}
    {{user.as_p}}
    {{profile.as_p}}
    <input type="submit">
    {% endif %}
</form>

{% endblock %}